### ISSUE TITLE
Contributions?

### ISSUE THREAD

**Issue by chickencoder** [siaflab/petal#2]
Loving Petal! I tried a few months ago to complete a project similar to this one but I'm very impressed with the simplicity of the language. I'm simply wondering if you intend to develop the project further, if so I would love to contribute my ideas (of which I have a couple features I'd love to see) and code.

**Comment by kn1kn1** [comment]
Thanks for the proposal! Though I'd like to keep Petal simple as possible and the project is not active, requested features may be merged with it.
