### ISSUE TITLE
Consider converting samples to .flac files

### ISSUE THREAD

**Issue by rbnpi** [siaflab/petal#3]
I have converted all the samples in Dirt-Samples to .flac files. This saves considerably on disk space, and works well. (Built in SP samples are all now .flac files). I used the free utility XLD on my Mac to do this.
This is a great system. Thanks for producing it.

**Comment by kn1kn1** [comment]
Done with commit https://github.com/siaflab/petal/commit/e487bb9aa304006948e41e8c930c0fca89c4fdb1 .
